name: take_home_assessment
description: PulseNow Flutter Assessment - Crypto Trading & Analytics Platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # HTTP
  http: ^1.1.0

  # Streaming
  web_socket_channel: ^3.0.3

  # UI
  cupertino_icons: ^1.0.6
  shimmer: ^3.0.0

  # Utilities
  intl: ^0.18.1

  # DI
  get_it: ^9.2.0

  equatable: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true